const baseUrl = `http://192.168.1.19/api/`;
const loginRoute = `login`;
export const loginUrl = baseUrl + loginRoute;
const getAllStoresRoute = `store-user`;
export const storeUrl = baseUrl + getAllStoresRoute;
const getAllCategoryRoute = `categories`;
export const categoryUrl = baseUrl + getAllCategoryRoute;
const getAllCouponRoute = `coupon-user`;
export const couponUrl = baseUrl + getAllCouponRoute;
const getAllProductRoute = `products`;
export const productUrl = baseUrl + getAllProductRoute;
const getAllFeaturedStoresRoute = `store-featured`;
export const featuredStores = baseUrl + getAllFeaturedStoresRoute;
const getAllFeaturedCouponsRoute = `coupon-user`;
export const featuredCoupons = baseUrl + getAllFeaturedCouponsRoute;
const getAllCategoriesRoute = `category-user`;
export const AllCategories = baseUrl + getAllCategoriesRoute ;
const searchStoreRoute=`search-store`
export const searchStore = baseUrl + searchStoreRoute
